import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portafolio Diego Alejandro Ocampo Madroñero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        {children}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Prevenir el error de hidratación causado por extensiones del navegador
              document.body.setAttribute('suppressHydrationWarning', 'true');
            `,
          }}
        />
      </body>
    </html>
  );
}
